import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  header: {
    backgroundColor: '#fff',
    paddingTop: 20,
    paddingBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 5,
    borderBottomColor: '#000',
    borderBottomStyle: 'solid',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#000',
  },
  characterList: {
    padding: width * 0.05,
    paddingHorizontal: width * 0.02,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  characterContainer: {
    width: width * 0.4,
    backgroundColor: '#FFF',
    borderRadius: 10,
    padding: 10,
    marginVertical: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  characterImage: {
    width: '100%',
    height: width * 0.3,
    borderRadius: 10,
  },
  characterName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginTop: 5,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  deleteButton: {
    color: 'red',
  },
  advanceButton: {
    color: '#6A5ACD',
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    paddingVertical: 10,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    elevation: 5,
  },
  navButtonHome: {
    flex: 0,
    alignItems: 'center',
  },
  navButtonAddContainer: {
    flex: 1,
    alignItems: 'center',
  },
  navButtonAdd: {
    backgroundColor: '#006400',
    padding: 10,
    borderRadius: 50,
    elevation: 5,
  },
  navButtonProfile: {
    flex: 1,
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '80%',
    maxHeight: '70%',
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  input: {
    height: 40,
    borderColor: '#6A5ACD',
    borderWidth: 2,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginBottom: 15,
    backgroundColor: '#fff',
    fontSize: 16,
  },
  imagePickerText: {
    color: '#6A5ACD',
    marginBottom: 10,
    fontWeight: 'bold',
  },
  selectedImage: {
    width: '100%',
    height: 100,
    borderRadius: 10,
    marginVertical: 10,
    borderColor: '#6A5ACD',
    borderWidth: 2,
  },
  diceResultContainer: {
    position: 'absolute',
    top: '75%',
    left: '50%',
    transform: [{ translateX: -width * 0.45 }, { translateY: -height * 0.1 }],
    alignItems: 'center',
    backgroundColor: 'transparent',  // Fundo transparente
    paddingVertical: 20,
    paddingHorizontal: 30,
    borderRadius: 15,
    borderColor: '#ddd',
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 7,
  },
  diceResultText: {
    fontSize: 28,
    fontWeight: '700',
    color: '#fff',  // Números em branco
    textAlign: 'center',
  },
  diceIcon: {
    marginTop: 15,
    fontSize: 40,
    color: '#6A5ACD',
  },
  detailsContainer: {
    padding: 2,
    backgroundColor: '#f8f8f8',
    borderRadius: 10,
    marginVertical: 10,
    elevation: 2,
  },
  detailsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  detailsInputContainer: {
    marginBottom: 15,
  },
  modalView: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -width * 0.4 }, { translateY: -height * 0.35 }],
    width: '80%',
    maxHeight: '70%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },

  navButtonAddContainerAnimated: {
    flex: 1,
    alignItems: 'center',
  },
  navButtonAddAnimated: {
    backgroundColor: '#006400',
    padding: 12,
    borderRadius: 50,
    elevation: 6,
    transform: [{ scale: 1 }],
  },

  diceSelectorContainer: {
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  diceNumberContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  diceControl: {
    backgroundColor: '#f0f0f0',
    padding: 8,
    borderRadius: 5,
    margin: 5,
  },
  diceControlText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  diceCount: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },

  // Botão de fechar
  closeButton: {
    backgroundColor: '#006400', // Cor verde
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 50,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 15,
  },
  closeButtonText: {
    color: '#fff', // Texto branco
    fontSize: 18,
    fontWeight: 'bold',
  },
});
